In [4]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

class one_hot_encoder():
    def __init__(self, categories):
        self.label_encoder = LabelEncoder()
        self.label_encoder.fit(categories)
        self.onehot_encoder = OneHotEncoder(sparse=False)
        
    def encode(self, values):
        self.integer_encoded = self.label_encoder.transform(values)
        self.integer_encoded = self.integer_encoded.reshape(len(self.integer_encoded), 1)
        self.onehot_encoded = self.onehot_encoder.fit_transform(self.integer_encoded)
        return self.onehot_encoded
    
    def invert(self, values):
        integer_encoded = []
        for value in values:
            integer_encoded.append(np.argmax(value))
        inverted = self.label_encoder.inverse_transform(integer_encoded)
        return inverted
ohe = one_hot_encoder(["1","2","3","4","5","6"])
print(ohe.encode(["1","2","3","4","5","6"]))


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


/home/xr-10/anaconda3/envs/py27/lib/python2.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [ ]:
def create_mlp(input_dim, network=[8,4] regress=False, one_hot=False, categories=None):
    if one_hot:
        ohe = one_hot_encoder(categories)
        dim = len(categories)
        
    # define our MLP network
    model = Sequential()
    model.add(Dense(network[0], input_dim=dim, activation="relu"))
    for i in network[1:]:
        model.add(Dense(i, activation="relu"))

    # check to see if the regression node should be added
    if regress:
        model.add(Dense(1, activation="linear"))

    # return our model
    return model