In [5]:
from keras.datasets import mnist

Using TensorFlow backend.


In [6]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()


11493376/11490434 [==============================] - 1s 0us/step


In [8]:
X_train[0].shape


(28, 28)

In [9]:
X_train = X_train.reshape(60000,28,28,1)
X_test = X_test.reshape(10000,28,28,1)

In [10]:
from keras.utils import to_categorical
#one-hot encode target column
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [14]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
#create model
model = Sequential()
#add model layers
model.add(Conv2D(64, kernel_size=3, activation="relu", input_shape=(28,28,1)))
model.add(Conv2D(32, kernel_size=3, activation="relu"))
model.add(Flatten())
model.add(Dense(10, activation="softmax"))

Instructions for updating:
Colocations handled automatically by placer.


In [15]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [16]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3)


Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 7s 123us/step - loss: 2.2549 - acc: 0.8361 - val_loss: 0.0780 - val_acc: 0.9762
Epoch 2/3
60000/60000 [==============================] - 5s 87us/step - loss: 0.0735 - acc: 0.9785 - val_loss: 0.0862 - val_acc: 0.9717
Epoch 3/3
60000/60000 [==============================] - 5s 85us/step - loss: 0.0485 - acc: 0.9848 - val_loss: 0.0794 - val_acc: 0.9764


In [17]:
model.predict(X_test[:4])


array([[9.9362046e-11, 1.4519587e-12, 5.3944188e-10, 5.2281312e-06,
        3.8791777e-16, 1.4730863e-12, 4.9622581e-18, 9.9999475e-01,
        6.5322781e-14, 7.8635182e-10],
       [1.4836056e-05, 6.9237353e-06, 9.9997711e-01, 2.7969815e-09,
        1.8818203e-09, 1.0090550e-11, 8.6944561e-07, 5.2792352e-13,
        2.7138867e-07, 3.9724915e-17],
       [1.7473017e-08, 9.9975783e-01, 1.0576865e-05, 1.3410380e-07,
        8.1099395e-05, 1.8176303e-05, 1.8827601e-06, 4.0054561e-05,
        8.9750698e-05, 4.1660402e-07],
       [9.9999273e-01, 2.6746142e-11, 2.6392524e-07, 8.7028327e-12,
        7.0687367e-10, 5.4717257e-09, 1.2303759e-07, 3.5483576e-09,
        1.9730193e-09, 6.9135695e-06]], dtype=float32)

In [18]:
y_test[:4]


array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)